export { default as Upload } from 'antd/lib/upload'
export { default as Icon } from 'antd/lib/icon'
export { default as message } from 'antd/lib/message'
export { default as Select } from 'antd/lib/select'
export { default as InputNumber } from 'antd/lib/input-number'

import 'antd/lib/upload/style/css'
import 'antd/lib/icon/style/css'
import 'antd/lib/message/style/css'
import 'antd/lib/select/style/css'
import 'antd/lib/input-number/style/css'
